# ---------------------------------------------------------------------------
# Data sources: use the default VPC and always resolve the latest Ubuntu
# 22.04 LTS AMI for the selected region (no hard-coded, region-locked AMI).
# ---------------------------------------------------------------------------
data "aws_vpc" "default" {
  default = true
}

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# ---------------------------------------------------------------------------
# SSH key pair: generated by Terraform so the project is self-contained and
# reproducible. The private key is written locally for Ansible and is
# git-ignored — it never touches version control.
# ---------------------------------------------------------------------------
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "this" {
  key_name   = var.key_pair_name
  public_key = tls_private_key.ssh.public_key_openssh
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.ssh.private_key_pem
  filename        = "${path.module}/${var.private_key_path}"
  file_permission = "0600"
}

# ---------------------------------------------------------------------------
# Modules: security group (network) and EC2 instance (compute).
# ---------------------------------------------------------------------------
module "network" {
  source = "./modules/network"

  name              = var.project_name
  vpc_id            = data.aws_vpc.default.id
  allowed_ssh_cidr  = var.allowed_ssh_cidr
  allowed_http_cidr = var.allowed_http_cidr
}

module "compute" {
  source = "./modules/compute"

  name                   = var.project_name
  ami_id                 = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  key_name               = aws_key_pair.this.key_name
  vpc_security_group_ids = [module.network.security_group_id]
}

# ---------------------------------------------------------------------------
# Generate the Ansible inventory from live infrastructure state. This
# replaces manual editing of the hosts file and keeps it always correct.
# ---------------------------------------------------------------------------
resource "local_file" "ansible_inventory" {
  content = templatefile("${path.module}/templates/inventory.tpl", {
    public_ip = module.compute.public_ip
    key_path  = abspath(local_sensitive_file.private_key.filename)
  })
  filename = "${path.module}/../ansible/inventory/hosts.ini"
}
